### ISSUE TITLE
Feature Request: In addition to specifying company logo, also specify company title

### ISSUE THREAD

**Issue by schaveyt** [afonsof/jenkins-material-theme#101]
First off, this theme is amazing and you have done a wonderful job!

I am applying your thing and using your site to specify a company logo as well. It works great! 

However, our company logo has a dark blue font in it transparent png...that well cannot be seen very well over top of any of the blue, light-blue or indigo color palettes.

The feature request is to allow the user to also specify a company title text and it color

One would them be able to say: Company Title="My Awesome Company" FontColor: White; FontSize: 10pt; align: right-of-logo

Thoughts?

**Comment by afonsof** [comment]
What about changing your logo font color?

**Comment by schaveyt** [comment]
Ha. I wish it could but it is not something I have control over. No matter, I have a goo enough solution that seems to work now.

You can close this issue if you like

**Comment by schaveyt** [comment]
Apparently I have the ability to close it. Perfecto!
