### ISSUE TITLE
SSL certificate is broken rendering them useless

### ISSUE THREAD

**Issue by ssbarnea** [afonsof/jenkins-material-theme#105]
It seems that SSL certificates is brokened, which makes the "CDN" useless:
https://afonsof.com/jenkins-material-theme/dist/material-brown.css

**Comment by darkwinternight** [comment]
This really needs to be fixed.

**Comment by afonsof** [comment]
afonsof.com/jenkins-material-theme is hosted at GitHub and is a shortcut for afonsof.github.io/jenkins-material-theme. I bought a certificate for the domain afonsof.com however this is not working properly because this shortcut. Anyone with experience in this area can help me?

**Comment by ssbarnea** [comment]
I would host it on S3 as you can get SSL for free and real-reliability. The cost of hosting these files would probably be smaller than a certificate anyway.
Also, if you use S3 you can also log the requests in case you want to get some analytics after that.

**Comment by darkwinternight** [comment]
Or forget the custom domain and use SSL on GitHub pages. https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by ssbarnea** [comment]
@darkwinternight Indeed, another place where less (complexity) is more (reliability).

**Comment by frekele** [comment]
You can use the github domain, simply like this:

https://raw.githubusercontent.com/

https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-red.css

**Comment by darkwinternight** [comment]
Yes @frekele, that is what most people are probably doing now. It seems that @afonsof wants a custom domain though.

**Comment by afonsof** [comment]
In fact I just want everything working @darkwinternight. So all we need to do is to change the docs to point to raw.github... excellent idea @frekele!

**Comment by afonsof** [comment]
Changed in the docs. Please use `https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-{{your-color-name}}.css`
