### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/plain

### ISSUE THREAD

**Issue by meinnamehier** [afonsof/jenkins-material-theme#106]
I am using Jenkins V 2.46.1

I can access the css files (e.g. https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css), put when I apply them using the Simple Theme Plugin, nothing changes.

When I use another theme, like this one, it works: http://jenkins-contrib-themes.github.io/jenkins-neo-theme/dist/neo-light.css

**Comment by meinnamehier** [comment]
In the console output of Chrome I get this: 
Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css".

**Comment by timbru31** [comment]
Firefox even does block this "malicious" request: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

**Comment by wbagdon** [comment]
You can use [rawgit](https://rawgit.com/) to provide the correct MIME type
https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css

```
$ curl -I https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css
HTTP/1.1 200 OK
Date: Sat, 08 Apr 2017 17:16:16 GMT
Content-Type: text/css;charset=utf-8
Connection: keep-alive
X-Content-Type-Options: nosniff
X-Robots-Tag: none
Access-Control-Allow-Origin: *
ETag: "a2b5c91a2b090c33ba5df33035ea4fe6f34b969e"
Cache-Control: max-age=315569000, immutable
Vary: Accept-Encoding
RawGit-Cache-Status: HIT
Server: NetDNA-cache/2.2
X-Cache: HIT
```

**Comment by afonsof** [comment]
Changed to use CDN
