### ISSUE TITLE
Styles doesn't change in Jenkins 2.53

### ISSUE THREAD

**Issue by SalahAdDin** [afonsof/jenkins-material-theme#107]
Hi guys

I installed the latest `jenkins` version, which is `2.53`.

I proceeded to install the styles in my project:
![seleccion_316](https://cloud.githubusercontent.com/assets/5034215/24860050/72ebfb12-1dfb-11e7-8d6f-8f7c01d45713.png)

But styles doesn't change:
![configurar el sistema jenkins - chromium_317](https://cloud.githubusercontent.com/assets/5034215/24860086/9baacd8a-1dfb-11e7-86ff-afb6e14a44bb.png)

Which is the problem here?

**Comment by benathmane** [comment]
Hello,

Try : http://afonsof.com/jenkins-material-theme/dist/material-light.css
or :
1. generate your theme (file.css for example) : http://afonsof.com/jenkins-material-theme/
2. Copy the file css (file.css) content into your $JENKINS_HOME/userContent/
3. In your jenkins configuration : URL of theme CSS = http://localhost/userContent/file.css

crdlt
AB

**Comment by afonsof** [comment]
Hi @SalahAdDin please use the CDN file: https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-{{your-color-name}}.css

**Comment by SalahAdDin** [comment]
@afonsof Can you update the documentation please?

**Comment by timbru31** [comment]
@SalahAdDin It's updated :)

**Comment by SalahAdDin** [comment]
In the official web page also, isn't it?

**Comment by yangcvo** [comment]
我也存在同样的问题。 填写https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css 这个地址 并没有生效。
