### ISSUE TITLE
Console Input Conflicts with ANSIColor Plugin

### ISSUE THREAD

**Issue by TechExhibeo** [afonsof/jenkins-material-theme#11]
Hey,
Your theme is so awesome, I liked it :dancer: 
But i have the issue with Console input
I am using ANSI Color Plugin for colorful logs.
and the issue is that colored lines have a banner type background which hide the upper line text
here is the screenshot
http://i.imgur.com/i5gelA3.png 

full console input here
http://jenkins.legacyserver.in/job/AOSP-CAF-MM_armani_%20deepak/3/console

thank you

**Comment by TechExhibeo** [comment]
Fixed it changing padding in .css file

padding:10px 20px      to        padding:5px 20px

Thank you for the Theme

**Comment by afonsof** [comment]
Problem fixed in prod version. Thanks @TechExhibeo!

**Comment by afonsof** [comment]
Please give a star to this project :star2: :smile:
