### ISSUE TITLE
Body overlaps header when scrolling

### ISSUE THREAD

**Issue by rbywater** [afonsof/jenkins-material-theme#13]
On Chrome 47 (Mac) & Jenkins 1.580.3, the body of the Jenkins page is overlaying the header portion of the page when scrolling as per the attached screenshot.

Note that I'm using Stylish at the moment so not sure if that's part of the cause.

<img width="1440" alt="screen shot 2016-01-26 at 8 34 58 am" src="https://cloud.githubusercontent.com/assets/384963/12562021/cde21d48-c407-11e5-801c-ef1e970a2a8c.png">

**Comment by afonsof** [comment]
Thanks @rbywater.

It's a real bug. Let me add some z-index to solve that.

:angry: :bug:

**Comment by afonsof** [comment]
Fixed! Please give a star if possible :star2:
