### ISSUE TITLE
Chrome could not recognize the dist in gh-pages branch.

### ISSUE THREAD

**Issue by acrazing** [afonsof/jenkins-material-theme#130]
Env: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`

The preview of the network panel:

<img width="778" alt="qq20170727-152213 2x" src="https://user-images.githubusercontent.com/10029810/28658882-e56fba8c-72df-11e7-87ce-37df021abc58.png">

And the theme is not effective, if I format the code in Sources panel, then all is work.

This is a bug about chrome it self?

**Comment by afonsof** [comment]
I don't understand what is your problem. Could you be more specific?
