### ISSUE TITLE
Unable to revert back to original Jenkins default theme

### ISSUE THREAD

**Issue by colinbut** [afonsof/jenkins-material-theme#169]
Hi,

Firstly, thanks for this material theme, I really like it. 😃 

I was experimenting with a custom theme from your website by following steps outlined in this blog link: https://devopscube.com/setup-custom-materialized-ui-theme-jenkins/ and it worked really well (both options).

However, when I try to revert back by deleting the entry made in the Theme Configuration for the Simple Theme plugin under **Configure System** - I couldn't. I tried all combinations of "Apply" & "Save" after hitting the 'delete' button but still after the custom themes still remains.

I was running Jenkins in a Docker container so I tried to stop & restart the container but no luck. 
I appreciate this might not sound like an issue to do with the project but was wondering whether you have experienced similar issue before & if so how to resolve, thanks.

**Comment by nmgds** [comment]
try adding any new element (empty), delete the old one and save

**Comment by colinbut** [comment]
@nmgds thanks. your solution has worked
