### ISSUE TITLE
CodeMirror not using monospaced font

### ISSUE THREAD

**Issue by jhasse** [afonsof/jenkins-material-theme#19]
The CodeMirror editor textarea which is for example used by "Execute Shell script" is using Roboto, but it should rather use a monospaced font ;)

**Comment by afonsof** [comment]
What plugin do I have to install to see the error?

**Comment by jhasse** [comment]
None, the build step "execute shell script" should be part of the standard jenkins installation.

**Comment by afonsof** [comment]
You mean here, correct?
![image](https://cloud.githubusercontent.com/assets/805511/12687321/45a578b0-c6b6-11e5-8b66-f0ed24c798c8.png)

**Comment by afonsof** [comment]
How about
![image](https://cloud.githubusercontent.com/assets/805511/12687746/e7549770-c6b8-11e5-8447-00010d24906a.png)

**Comment by jhasse** [comment]
Awesome!

**Comment by afonsof** [comment]
Done: version 1.1.3
