### ISSUE TITLE
Provide an option to disable animations

### ISSUE THREAD

**Issue by cobexer** [afonsof/jenkins-material-theme#22]
Maybe as a real Jenkins plugin that could be updated using the normal update center?

The problem for me is that our users can't reach fonts.googleapis.com and afonsof.github.io from where they access the Jenkins server.

Also it would be awesome if there were no animated graphics. Our clients have to be accessed using Remote Desktop and Firefox for example uses a ton of CPU to render the gif animations (It uses way less CPU for the CSS based animations) also since you use distinct shapes for yello-anime.gif and yellow.png the animations don't add anything.

**Comment by jhasse** [comment]
If I'm not mistaken this theme is only using SVG files, not gifs: https://github.com/afonsof/jenkins-material-theme/tree/master/images

**Comment by cobexer** [comment]
@jhasse you are right, the lack of gifs is a big reason for me to use this theme :)
With the gifs in the original jenkins theme the animations are necessary because they look identical if I were to disable gif animations in my browser.
With this theme however the animations are not needed because a Yellow and a Yellow animated (in progress or something) can be easily distinguished.

I hope this explains my reference to the gif files :)

**Comment by jhasse** [comment]
Ah I understand :)

I guess it would be really good to make this theme into a dedicated Jenkins plugin then, since a configuration option could then be added to disable things like animations. I like them though! Not having any CPU issues in Firefox with them.

**Comment by cobexer** [comment]
Well animations are one of those things...
IMO the animated items are of no interest to me - while they are animated I don't care about them, but they grab my attention. When the build is finally done and may be interesting because it failed or has test results - they are not animated anymore.

About that CPU use: Open 5 or more tabs, access your browser over Remote Desktop note CPU use multiply by the number of developers. Then cry for all the CPU cycles that your VM server has to spend to do really important stuff like animating icons... maybe you don't see it because your browser has access to one of those fancy GPUs (any actually because VMs don't have real GPUs). ;)

**Comment by afonsof** [comment]
Guys, thanks for the suggestions! I guess both of them are interesting to implement. What about splitting it in 2 different issues?
* Disable animation option
* Created a dedicated plugin for this theme

**Comment by jhasse** [comment]
Yes, good idea. I've published the Python plugin to Jenkins in the past, so I can help with the latter one :)

**Comment by afonsof** [comment]
Done. Version 1.1.7

**Comment by cobexer** [comment]
Awesome thanks!
