### ISSUE TITLE
Build node 'context' menu is broken

### ISSUE THREAD

**Issue by kutzi** [afonsof/jenkins-material-theme#23]
When I access the 'context' menu of a build node (i.e. the small down arrow right to it)
the menu is rendered at the top of the page instead of next to the node

**Comment by kutzi** [comment]
![screenshot from 2016-02-01 11-19-36](https://cloud.githubusercontent.com/assets/175061/12714594/8aa278dc-c8cd-11e5-83cf-da376401e4b3.png)

**Comment by afonsof** [comment]
Thanks a lot for @kutzi! I've noticed that the left menu z-index is wrong. Fixing it as soon as possible!

**Comment by afonsof** [comment]
Fixed. Version 1.1.4

**Comment by afonsof** [comment]
@kutzi please, give us a star :star2:
:smile:

**Comment by kutzi** [comment]
Better - now it displays on the right place - but it's still rendered transparent - i.e. elements beneath it are showing through

IMO it should be opaque
