### ISSUE TITLE
Missing Icon for Not built (aborted builds)

### ISSUE THREAD

**Issue by cobexer** [afonsof/jenkins-material-theme#24]
`<img title="Not built" src="/static/c82d2d81/images/16x16/nobuilt.png" alt="Not built" tooltip="Not built" style="width: 16px; height: 16px; " class="icon-nobuilt icon-sm">`

**Comment by cobexer** [comment]
![notbuilt](https://cloud.githubusercontent.com/assets/460721/12714603/fc001982-c8d5-11e5-9a70-036bb11ebeb9.png)

**Comment by afonsof** [comment]
Thanks a lot for filing this issue! I'll take a look at it as soon as possible!
:smile:

**Comment by afonsof** [comment]
Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by cobexer** [comment]
Yes, unless that involves creating icons (I'm no designer :) ).
But it will be a few hours before I can take a look at that...

**Comment by afonsof** [comment]
@cobexer I'd rather use the same icon we are using for not started builds. What do you think?
![image](https://cloud.githubusercontent.com/assets/805511/12734312/c550a932-c926-11e5-92f4-0ae144d9759e.png)

**Comment by cobexer** [comment]
Maybe, I also considered using the stop build icon.
Reusing the icon you propose would use it for three states already, but I'm not sure how important the distinction really is...

**Comment by afonsof** [comment]
The stop build icon is different. This one: 
![image](https://cloud.githubusercontent.com/assets/805511/12770361/f4d20a1c-ca06-11e5-8461-923e757d6c8e.png)

Jenkins uses the same icon for "never build" and "aborted"so I think we should use too.

**Comment by afonsof** [comment]
Fixed. Version 1.1.6
