### ISSUE TITLE
Dropdown menuSelector displays beneath the build history menu

### ISSUE THREAD

**Issue by znorris** [afonsof/jenkins-material-theme#32]
Clicking the dropdown (menuSelector) for an individual item in the build history results in the menu being displayed beneath the build history element. I've noticed this behaviour in other places as well when using the menuSelector. Tested in Chrome.

![screenshot 2016-02-02 at 21 55 34](https://cloud.githubusercontent.com/assets/995047/12772568/e76f8e08-c9f7-11e5-9d03-af1960355ece.png)

Great theme. Glad to be using it.

**Comment by afonsof** [comment]
Fixed. Version 1.1.8
