### ISSUE TITLE
Disabled projects show no icon

### ISSUE THREAD

**Issue by znorris** [afonsof/jenkins-material-theme#35]
I see in the legend that the disabled icon is there however, when a project is disabled I don't see that icon. Mousing over the space does show 'disabled'.

![screenshot from 2016-02-04 15-39-45](https://cloud.githubusercontent.com/assets/995047/12830650/0403c3ae-cb56-11e5-90bf-7d987988604b.png)

Jenkins: 1.642.1

Element:
`<img src="/static/0027ac25/images/32x32/disabled.png" alt="Disabled" tooltip="Disabled" style="width: 32px; height: 32px; " class="icon-disabled icon-lg" title="Disabled">`

**Comment by afonsof** [comment]
Fixed: Version 1.1.9

**Comment by afonsof** [comment]
@znorris please give us a star if possible :star2:
