### ISSUE TITLE
Cancel build button appears as gray block

### ISSUE THREAD

**Issue by Heldroe** [afonsof/jenkins-material-theme#5]
I am using Chrome 47 on Windows.
Jenkins version is 1.641, Simple Theme Plugin version is 0.3.

The cancel build button/icon appears as a gray block on both build executor and build history.

![Build executor](https://cloud.githubusercontent.com/assets/391215/11784384/3ae4b8f4-a27c-11e5-936c-6ca6db6b8a2d.png)
![Build history](https://cloud.githubusercontent.com/assets/391215/11784385/3ca53470-a27c-11e5-81ed-47e52326cdff.png)

**Comment by Heldroe** [comment]
Same thing for "Edit view" in the left menu of a specific view.

![Edit View](https://cloud.githubusercontent.com/assets/391215/11784665/e4e25040-a27d-11e5-8dd7-273d07b66909.png)

**Comment by afonsof** [comment]
Thanks @heldroe. Going to fix that.

**Comment by afonsof** [comment]
@Heldroe, please give a star to this repo if possible :)
