### ISSUE TITLE
is it possible to change console  background  ?

### ISSUE THREAD

**Issue by riuvshin** [afonsof/jenkins-material-theme#80]
Love the theme but dark console background makes my crying is it possible to change it? I want everything exactly as it is but just white console background and black or gray text on it.

**Comment by BonarBeavis** [comment]
[AnsiColor Plugin - Jenkins - Jenkins Wiki](https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin)

**Comment by SalahAdDin** [comment]
@BonarBeavis, good plug in, thank you.
