### ISSUE TITLE
Seems this theme doesn't really like the latest version of Jenkins.

### ISSUE THREAD

**Issue by chamunks** [afonsof/jenkins-material-theme#85]
![cham-screenshot](https://cloud.githubusercontent.com/assets/1068374/18842561/7252ac9e-83e3-11e6-881e-af511fb35f86.png)
Not entirely certain if you plan to make this available for the latest version of Jenkins or not.  

``` Page generated: Sep 26, 2016 4:15:51 PM UTCREST APIJenkins ver. 2.23 ```

**Comment by basecamp88** [comment]
How does this build configuration page look without the theme?

**Comment by chamunks** [comment]
I would accept PR's, it's been a while since I've needed this but I just wanted something that people could use instead of packing their sshd's into every damn container after hearing time and time again one process one container. 

I'll look over your fork when I get to a computer next.

**Comment by afonsof** [comment]
This is not happening here, take a look:
![image](https://cloud.githubusercontent.com/assets/805511/18888346/e6f9b97e-84c5-11e6-958f-f854adeb7511.png)

Are you using the last version (1.3.1)?

**Comment by basecamp88** [comment]
This happens in general when you have long lines in scripts. The script box forces the left margin to extend, some items on the page follow the left margin.

This happens in vanilla theme in 2.x also.

**Comment by afonsof** [comment]
So it's not a Jenkinks Material Theme, right? Can I close this issue?

**Comment by chamunks** [comment]
@afonsof the original bug report that I had filed was for the Jenkins Material Theme, as soon as I take the reference to the CSS out of the jenkins configuration it normalises.
