### ISSUE TITLE
afonsof.com CSS linkes are broken due to SSL issue

### ISSUE THREAD

**Issue by colemickens** [afonsof/jenkins-material-theme#87]
<img width="1098" alt="screen shot 2016-10-14 at 12 25 01 am" src="https://cloud.githubusercontent.com/assets/327028/19378995/b3d301ae-91a4-11e6-820d-50378651a126.png">

**Comment by colemickens** [comment]
Workaround is to use: https://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-indigo.css

or: https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue.css

@afonsof Can you advise on which is better to use in the short-term?

**Comment by colemickens** [comment]
Actually, only this one works: https://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-indigo.css

I'm guessing raw.githubusercontent.com  serves the wrong mime-type.

**Comment by afonsof** [comment]
Thanks for informing me. Yesterday I bought a certificate and set it up on my domain. Unfortunately for some reason it's not working yet. Please use this URL temporarily: https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue.css

**Comment by colemickens** [comment]
Yeah, like I said, github doesn't serve that with the right mime-type and it doesn't seem to actually work.

The `https://jenkins-contrib-themes.github.io/jenkins-material-theme....` version works though.

**Comment by afonsof** [comment]
Yesterday I bought a certificate and set it up on my domain. Unfortunately for some reason it's not working yet.

For a while the best version to use is: https://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-indigo.css

You can also use a non https version at afonsof.com

**Comment by TobiX** [comment]
Well, you could use the [RawGit CDN](https://rawgit.com/) for hosting, like so: https://cdn.rawgit.com/afonsof/jenkins-material-theme/0eaa0f147de5844c422fd01b71f5d6bbd30bda6c/dist/material-red.css - Be aware that files on cdn.rawgit.com are cached permanently, so you need to use tags or commit IDs (so no automatic updates).

**Comment by kissifrot** [comment]
@afonsof , you should check the site https://www.ssllabs.com/ssltest/analyze.html?d=afonsof.com , you'll see the reasons why your certificate doesn't work.
BTW you can now use [Let's Encrypt](https://letsencrypt.org/) to get a free SSL certificate

**Comment by jszaszvari** [comment]
Get a letsencrypt certificate if your current one is not working.

The certificate thats being hosted is the one from *.github.com

**Comment by darkwinternight** [comment]
It's still not working by the way :) Chrome does not render the theme at all unless you accept the incorrect certificate.

**Comment by afonsof** [comment]
afonsof.com/jenkins-material-theme is hosted at GitHub and is a shortcut for afonsof.github.io/jenkins-material-theme. I bought a certificate for the domain afonsof.com however this is not working properly because this shortcut. Anyone with experience in this area can help me?

**Comment by darkwinternight** [comment]
@afonsof sure, I can help you set this up.

First of all, the certificate that is now being served belongs to github.com, not to afonsof.com. How did you set up this "shortcut" and what is the server running on afonsof.com?

**Comment by afonsof** [comment]
Changed in the docs. Please use `https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-{{your-color-name}}.css`
