### ISSUE TITLE
Thank you, Thank you, Thank you

### ISSUE THREAD

**Issue by vrenjith** [afonsof/jenkins-material-theme#89]
I am not sure how much I can thank you for spending efforts in getting this done for Jenkins. It is such an amazing improvement for our Jenkins instance and it looks great with this new theme. Thank you so much.

(didn't find a way to reach you to say this and hence this issue, please close it)

**Comment by afonsof** [comment]
You're very welcome @vrenjith. Feel free to open issues or contribute with pull requests.
