### ISSUE TITLE
Jenkins v2 pipeline code editor is broken

### ISSUE THREAD

**Issue by svscorp** [afonsof/jenkins-material-theme#90]
Hi @afonsof 

First of all, thank you very much for this initiative. Jenkins looks much better applying this theme! That's a great job done!

I'd like to report on one more issue (found by @jos4github), in addition to #73 

When editing pipeline as code, editor behaves very badly. You can't really figure out what are you typing or what character you will delete if you place your cursor in a middle of a work and press backspace.

Example:

I placed cursor as on screenshot:
![theme-bug-1](https://cloud.githubusercontent.com/assets/475464/20215553/516bdc5c-a815-11e6-8715-19612613295c.png)

I want to add one space, where do you think it applies? Look below :)
![theme-bug-2](https://cloud.githubusercontent.com/assets/475464/20215550/4d2666f8-a815-11e6-956f-52a336e52b6c.png)

Thank you.

**Comment by svscorp** [comment]
+ @jos4github

**Comment by wbagdon** [comment]
Which browser, OS, version of material-theme, and version of Jenkins are you using?
I resolved this issue with #62 previously and it still seems to work with Jenkins 2.31 and material-theme 1.3.2 on chrome windows

**Comment by jos4github** [comment]
We are Using Windows7 with Chrome (Version 54.0.2840.99 m (64-bit)) and also IE 11 on both browsers I have the same issue. Jenkins is running on a linux server.

Jenkins version is 2.32 (but with version 2.31 the issue was found) and material-theme is 1.3.2 as you can see in the screenshot. It also shows the that when you wants something to the end of the line the cursor is say 3 chars of track.

![materialthemeissue](https://cloud.githubusercontent.com/assets/23401086/20381176/91484e92-aca6-11e6-8f05-c5929208a6de.jpg)

**Comment by wbagdon** [comment]
The fonts are loaded client side from fonts.googleapis.com
Does your Win7 machine have access to the internet to download the font?
Does this page render correctly in your browser? https://developers.google.com/fonts/docs/getting_started
I suppose a fallback mono font should be used in case the Google font cannot be downloaded

**Comment by luka5z** [comment]
I experiencing the same exact problem with Firefox 50.1.0 and Ubuntu 16.04.

**Comment by wbagdon** [comment]
In Firefox if you inspect the editor, which font do you have listed?

![capture](https://cloud.githubusercontent.com/assets/1523424/21352751/f16606b2-c690-11e6-979d-b5f3625993a6.PNG)

**Comment by wbagdon** [comment]
Can you try building this and let me know if it works for you?
https://github.com/wbagdon/jenkins-material-theme/tree/linux_font_patch

I tried it with Firefox 50.1.0 and Ubuntu 16.10 and Win 7 and Firefox 50.1.0.

In case you cannot build it, here is the CSS file (just needs the extension changed back to CSS)

[material.css.txt](https://github.com/afonsof/jenkins-material-theme/files/663924/material.css.txt)

**Comment by svscorp** [comment]
@wbagdon the google dev page opens correctly. But we both experiencing same behavior. Need to reapply the theme and see if it is still the case.

Thank you very much returning on this and contributing your time to help with troubleshooting :)

**Comment by svscorp** [comment]
@wbagdon @jos4github 
Just checked. Same situation - clicked on the end of a line, cursor is somewhere 3.5 symbols back...

Win 7
Jenkins 2.37
material-css generated from the site as of now
Chrome: Version 55.0.2883.87 m

**Comment by wbagdon** [comment]
Generated from my fork and branch linux_font_patch?
I've bumped the version to 1.3.3 now if you want to rebuild and check that you have the right version.

**Comment by igisur** [comment]
I've tried attached "material.css.txt" and it does work with Firefox 50.1.0 on Win10

**Comment by wbagdon** [comment]
@svscorp @jos4github @luka5z 
Any luck with my attached file or building from my forked branch?

**Comment by svscorp** [comment]
@wbagdon @jos4github @afonsof 

I checked your attached file - it is working fine. Great Job!

Can it be merged / compiled to css in the main project?

**Comment by afonsof** [comment]
For sure @svscorp!

@wbagdon could you create a pull request?

**Comment by wbagdon** [comment]
Already created

**Comment by vadim-shb** [comment]
Hi. Thanks for your great work!
It seems like PL is accepted. Is the patch already in http://afonsof.com/jenkins-material-theme/dist/material-blue-grey.css?
Or it will be updated some time later?

**Comment by afonsof** [comment]
Hi @vadim-shb. The CSS file was just updated. Thank you!
