### ISSUE TITLE
the domain "afonsof.com" is dead?

### ISSUE THREAD

**Issue by hidekuro** [afonsof/jenkins-material-theme#92]
I accessed http://afonsof.com/jenkins-material-theme and got messages follow:
"The domain afonsof.com is no longer parked by GoDaddy".

<img width="500" alt="image" src="https://cloud.githubusercontent.com/assets/3986668/20818967/a469d8c2-b874-11e6-9c31-c90b42d7d9b9.png">

**Comment by afonsof** [comment]
Sorry I'm going to fix this.

**Comment by litrik** [comment]
FYI: I had to disable the Material theme because of this. The Jenkins UI had become extremely slow.

**Comment by ssbarnea** [comment]
I think that the the material theme kinda dematerialized due to godaddy issues.

**Comment by afonsof** [comment]
Problem solved. GoDaddy issues for sure!
