### ISSUE TITLE
HTTPS Broken

### ISSUE THREAD

**Issue by paralin** [afonsof/jenkins-material-theme#95]
Your HTTPS is invalid on your site

https://afonsof.com/jenkins-material-theme/dist/material-teal.css

**Comment by kissifrot** [comment]
I personally used
https://jenkins-contrib-themes.github.io/jenkins-material-theme/dist/material-teal.css
and it seems it works

**Comment by felipeplets** [comment]
@kissifrot the problem is that this link is outdated, the current version is 1.3.3 and the one you sent is 1.3.1. 

I gave up on using it online and hosted it myself.

**Comment by SimJoSt** [comment]
bump

**Comment by kissifrot** [comment]
See #87

**Comment by afonsof** [comment]
Changed in the docs. Please use `https://raw.githubusercontent.com/afonsof/jenkins-material-theme/gh-pages/dist/material-{{your-color-name}}.css`
